# -*- coding: utf-8 -*-
"""Sesión2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TR9uoRCyI6A1nx3aGmB5Zai_EmVX5Ozj
"""

import numpy as np # Traer al espacio de trabajo la libreria NumPy

arr = [7, 2, 9, 10]

type(arr)

arr_np = np.array(arr)
arr_np

type(arr_np)

result = arr_np * arr_np
result

matrix = arr_np * np.transpose(arr_np)
matrix

mat = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
mat

mat2D = np.array(mat)
mat2D

arr_np.shape

mat2D.shape

arr_3d = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]
mat3D = np.array(arr_3d)
mat3D.shape

mat3D[1,1,0] = "Lazaro"
mat3D

mat2D

mat2D[1, 4] = 2023
mat2D

mat2D[::2, ::3]

mat2D

mat2D[:,1]

temp0 = np.zeros((3,12),dtype=int)
temp0

temp1 = np.ones((3,12),dtype=int)
temp1

temp_rnd = np.random.randn(3,12)
temp_rnd

temp23 = temp0
temp23.fill(2023)
temp23

temp0

temp0.fill(0)
temp0

temp23

temp23 = np.copy(temp0)
temp23

temp23.fill(1942)
temp23

temp0

arr = mat2D.tolist()
arr

edades = np.array([19,20,19,19,20,21,20,19,21,20,19])
edades

np.histogram(edades, bins=[19, 20, 21])

arr_np = [1, 3, 67, 2, 0 ,23, 3,0,1,0,5,3,6,8,0,56,9,0,56,0]

arr_np

np.where(arr_np == 0)

res = [arr_np < 5]

import pandas as pd

s = pd.Series(['Matemáticas', 6, 'Economía', True, 'Inglés'])
s

p = s[1] + 7
p

l =  not s[3]
l

o = s[0]+ 7

s = pd.Series({'Matemáticas': 6.0, 'Economía': 4.5, 'Programación': 8.5})
s

s["Programación"]

s[2]

s.dtype

s.size

s.index

s[1:]

s["Economía":]

s.sum()

s.max()

s.describe()

s = s / 100
s = ((s ** 2) / (s + s)) * 1000
s

s >= 7.0

s[(s >= 8) & (s < 10) & (s != 8.5)]

import numpy as np

s = pd.Series([1, 2, None, 4, np.NaN, 6])
s

s.describe()

s1 = s.dropna()
s1

datos = {'nombre':['María', 'Luis', 'Carmen', 'Antonio'], 'edad':[18, 22, 20, 21], 'grado':['Economía', 'Medicina', 'Arquitectura', 'Economía'], 'correo':['maria@gmail.com', 'luis@yahoo.es', 'carmen@gmail.com', 'antonio@gmail.com'] }
datos

df = pd.DataFrame(datos)
df

col_names = ["nombre", "edad", "grado", "correo"]
row_names = [0,1,2,3]
nombre = ["Maria","Luis","Carmen","Antonio"]
edad = [18, 22, 20, 21]
grado = ["economia","medicina","arq","economia"]
correo = ["1@1.com", "2@2.com", "3@3.com", "4@4.com"]

df_1 = pd.DataFrame(np.transpose([nombre,edad,grado,correo]),columns=col_names,index=row_names)
df_1

val = np.random.randn(5,12)
df_2 = pd.DataFrame(val)
df_2

colesterol = df = pd.read_csv( 'https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesteroles.csv', sep=';', decimal=',')
colesterol

colesterol.to_csv("F:\lbustio\OneDrive\OneDrive - Universidad Iberoamericana, A.C\Escritorio\Diplomado\Sesión 1\test.csv",sep="*")

colesterol.shape

df = colesterol

df.info()

df.size

df.dtypes

df.head(3)

df.tail(3)

df

newcolnames = {"nombre" : "name",	"edad" : "age", "sexo" : "sex", "peso" : "weight", "altura" : "height", "colesterol" : "colesterol"}
newcolnames

df1 = df.rename(columns=newcolnames)
df1

df.loc[(1,5,7),("edad", "sexo")]

df.iloc[3:,4::2]

df

diabetes = pd.Series([True,False,True,True,False,False],dtype=bool)
diabetes

df["diabetes"] = diabetes
df

df.isnull().sum()

df.info()

df.describe()

df["peso"].fillna(np.mean([69.66, 79.77]), inplace=True)
df

df.isna().sum()

df.info()

df.loc[(df["peso"] >= 70) & (df["peso"] <= 75) & (df["altura"] > 1.7) & (df["colesterol"] >= 200), "colesterol"]=True

df

df

df["altura"] = df["altura"]*100
df

df["sexo" == 'M']

df

colesterol = df.pop("colesterol")
df

colesterol

df["colesterol"] = colesterol

df

colesterol

salida = df.pop(("colesterol", "peso"))

df = pd.read_csv( 'https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesterol.csv')

df

df = df.append(pd.Series(['Carlos Rivas', 28, 'H', 89.0, 1.78, 245.0], index=['nombre','edad','sexo','peso','altura','colesterol']), ignore_index=True)

df

df1 = df.drop([1,3])
df1

df.dropna(inplace=True)
df

df["altura"] = df["altura"]*100
df

df.groupby("sexo").groups

df["talla"] = "Chico"
df

df.loc[(df["altura"] > 160) & (df["altura"] <= 175), "talla"] = "Medio"
df

df.loc[df["altura"] > 175, "talla"] = "Alto"
df

df.groupby(["sexo","talla",]).get_group(("H","Chico"))

datos = {'nombre':['María', 'Luis', 'Carmen'], 'edad':[18, 22, 20], 'Matemáticas':[8.5, 7, 3.5], 'Economía':[8, 6.5, 5], 'Programación':[6.5, 4, 9]}

datos

eje = pd.DataFrame(datos)
eje

df1 = eje.melt(id_vars=['nombre', 'edad'], var_name='asignatura', value_name='nota')
df1

print(df1.pivot(index='nombre', columns='asignatura', values='nota'))

p = 1.236589

print(round(p,2))

import io
from google.colab import files

uploaded = files.upload()

uploaded

df = pd.read_csv(io.BytesIO(uploaded["colesteroles.csv"]), sep=";", decimal=",")
df